### ISSUE TITLE
Where I can find the paper?

### ISSUE THREAD

**Issue by Liuzhengfa88** [narendoraiswamy/Active-Domain-Adaptation#1]
I can't find the paper "Active learning for few shot semi-supervised Domain adaptation"

**Comment by narendoraiswamy** [comment]
Hello Liuzhengfa88,

Thank you for your interest in our work. We have made certain modifications in our method and the paper has been accepted at the CVPR L2ID workshop 2021. We will release the camera ready version of the paper soon on arxiv and link it up. 

Thank you.
